databases:
  - name: feedboard
    databaseName: feedboard
    user: nicmackenzie

services:
  - type: web
    name: feedboard
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: feedboard
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
